- name: Play level variables
  hosts: all
  vars:
    URL: test.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}

- name: Play level variable from a file
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}

- name: Tasks levels variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}
      vars:
        URL: test1.copy.com

