- name: Play level variables
  hosts: all
  vars:
    URL1: test.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL1 ={{URL1}}

- name: Play level variable from a file
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}


- name: Tasks level variable
  hosts: all
  tasks:
    - name: Print URL
      ansible.builin.debug:
        msg: URL ={{URL}
      vars:
        URL: test1.type.com

- name: Tasks levels variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL1 ={{URL1}}
      vars:
        URL1: test1.copy.com

