- name: Play level variables
  hosts: all
  vars:
    URL: play.example.com
    URL1: test.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}
        msg: URL1 ={{URL1}}

- name: Play level variable from a file
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}
