- name: Demo on loop
  hosts: localhost
  tasks:
    - name: Print Color Name
      debug:
        msg: Color Name = {{item}}
      loop:
        - red
        - blue
        - yellow

    - name: Print Color Name and Invetory Count
      debug:
        msg: Color Name = {{item.name}} , Available Count = {{item.count}}
      loop:
        - {name: red, count: 10}
        - {name: blue, count: 20}
        - {name: Yellow, count: 30}
