- name: Demo on loop
  hosts: localhost
  tasks:
    - name: Print Color Name
      debug:
        msg: Color Name = {{item}}
      loop:
        - red
        - blue
        - yellow

- name: Print coloy Name with inv
  debug:
    msg: Color Name = {{item.name}}, Avaiable count = {{item.count}}
    loop:
      - {name: red, count: 10}
      - {name: blue, count: 9}
      - {name: yellow, count: 8}
