- name: Print Frontend
  ansible.builtin.debug:
    msg: Frontend
 # yum install nginx -y
 # systemctl enable nginx
 # systemctl start nginx
#  Let's download the HTDOCS content and deploy under the Nginx path.
# curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
 #Deploy in Nginx Default Location.
 # cd /usr/share/nginx/html
  # rm -rf *
  # unzip /tmp/frontend.zip
  # mv frontend-main/* .
  # mv static/* .
  # rm -rf frontend-main README.md
  # mv localhost.conf /etc/nginx/default.d/roboshop.conf
# Finally restart the service once to effect the changes.
-
- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: download and extract frontend
  ansible.builtin.unarchive:
    src: http://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy frontend pkg and move
  ansible.builtin.copy:
      src: /tmp/frontend-main/static/
      dest: /usr/share/nginx/html/
      remote_src: yes

- name: Copy Roboshop cfg
  ansible.builtin.copy:
     src: roboshop.conf
     dest: /etc/nginx/default.d/roboshop.conf

- name: Start service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes




