- name: Print Catalogue
  ansible.builtin.debug:
    msg: Catalogue

- name: Configure Yum repos
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install Node
  ansible.builtin.yum:
    name:
       - nodejs
       - gcc-c++
    state: installed

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop
    comment: Add the roboshop user

- name: Download and extract the packages
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/catalogue/archive/main.zip
    dest: /home/roboshop/
    become_user: roboshop
    
