- name: Print Catalogue
  ansible.builtin.debug:
    msg: Catalogue

- name: Configure Yum repos
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install Node
  ansible.builtin.yum:
    name:
       - nodejs
       - gcc-c++
    state: installed